[project]
name="langchain_tutorial"
version="0.1.0"
description="LangChain learning project"

requires-python = ">=3.10"

dependencies = [
    "chromadb>=1.3.4",
    "langchain>=1.0.5",
    "langchain-community>=0.4.1",
    "langchain-core",
    "langchain-deepseek",
    "langgraph>=1.0.2",
]
